version: "3.2"
services:
  redis-cluster-1:
    container_name: redis-cluster-1
    image: redis:latest
    ports:
      - "8001:6379"
    volumes:
      - D:\STS\redis_present\cluster\cluster-1.conf:/usr/local/etc/redis/redis.conf
      - D:\STS\redis_present\cluster\clsuter-1-sysctl.conf:/etc/sysctl.conf
    networks:
      - cluster-network
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  redis-cluster-2:
    container_name: redis-cluster-2
    image: redis:latest
    ports:
      - "8002:6379"
    volumes:
      - D:\STS\redis_present\cluster\cluster-2.conf:/usr/local/etc/redis/redis.conf
      - D:\STS\redis_present\cluster\clsuter-2-sysctl.conf:/etc/sysctl.conf
    networks:
      - cluster-network
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  redis-cluster-3:
    container_name: redis-cluster-3
    image: redis:latest
    ports:
      - "8003:6379"
    volumes:
      - D:\STS\redis_present\cluster\cluster-3.conf:/usr/local/etc/redis/redis.conf
      - D:\STS\redis_present\cluster\clsuter-3-sysctl.conf:/etc/sysctl.conf
    networks:
      - cluster-network
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
networks:
  cluster-network:
    driver: bridge

